---
- name: Gather interface status from Cisco switches
  hosts: switches
  gather_facts: no
  # collections:
  #   - community.network

  tasks:
    - name: "1010 - Collect facts from Cisco devices"
      ios_facts:
        gather_subset:
          - interfaces
      register: interface_facts

    - name: "1010 - OUTPUT INTERFACE FACTS"
      debug:
        var: interface_facts