
---
- name: Gather interface status from Cisco switches
  hosts: switches
  gather_facts: yes

  tasks:

    - name: Run show version on remote devices
      ios_command:
        commands: 
          - show ip interface brief
      register: interface_output

    # - name: Show NET_TEXTFSM Path
    #   debug:
    #     msg: "NET_TEXTFSM is {{ lookup('env', 'NET_TEXTFSM') }}"

    # - name: Parse interface data using TextFSM
    #   ansible.builtin.set_fact:
    #     parsed_interfaces: "{{ interface_output.stdout[0] | parse_cli_textfsm('ntc-templates/ntc_templates/templates/cisco_ios_show_ip_interface_brief.textfsm') }}"


    - name: Read in parse_genie role
      include_role:
        name: clay584.parse_genie

    - name: Parse interface data using genie
      set_fact:
        parsed_interfaces: "{{ interface_output.stdout[0] | parse_genie(command='show ip interface brief', os='ios') }}"


    - name: "1010 - OUTPUT DEVICE INFO"
      debug:
        var: parsed_interfaces.interface["Loopback1"]


    # - name: Run show interface description command
    #   ios_command:
    #     commands: show interface description
    #   register: raw_output

    # - name: Parse the output using cli_parse
    #   ansible.netcommon.cli_parse:
    #     command: show interface description
    #     data: "{{ raw_output.stdout[0] }}"
    #   register: parsed_output

    # - name: Display parsed structured output
    #   debug:
    #     var: parsed_output
