---
- name: Play A
  hosts: localhost
  gather_facts: false
  vars:
    device_type: "Router"
    devices: 
      - "R1"
      - "R2"
      - "R3"
    device_creds:
      user_name: "NetG"
      password: "India"
    ip: " 10.2.3.4 "

  tasks:
    # - name: "1010 - OUTPUT DEVICE TYPE"
    #   debug:
    #     # msg: "{{ device_type | upper | lower | upper }}"
    #     # var: "device_type.upper()"
    #     # msg: "{{ device_type.upper() }}"
    #     msg: "Device name is {{ device_type.upper().replace('ROU', 'Myrouter') }}"

    # - name: "1020 - OUTPUT DEVICES DATA"
    #   debug:
    #     var: "devices[1]"

    - name: "1030 - OUTPUT DEVICES CREDS"
      debug:
        var: "device_creds['user_name'][0:1]"

    # - name: "1030 - OUTPUT DEVICES CREDS"
    #   debug:
    #     var: "'.'.join(ip.strip().split('.'))"